### PR TITLE
Clone page

### PR DESCRIPTION
**Pull request by balerum03**
This page was created using bootstrap and it is a copy of newsweek.com

### CODE REVIEW

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi @balerum03 ! 👋 
You have done a wonderful job with this project so far! 👏 👏 Great job using bootstrap classes in lieu of CSS styling for the majority of the project! 👍 It is clear that you have a good understanding of Bootstrap. 🎖️ 🌟    There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

### Large Screen

- **Navigation Bar**

- [ ] Please give a little more padding below the navigation bar. Currently, the elements below it are too close. 
Your clone 👇 
Screen Shot 2020-07-01 at 12 02 48 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 03 05 AM
- **Featured Stories**

- [ ] Please add a bit more padding between the articles.
The original page 👇 
Screen Shot 2020-07-01 at 12 04 17 AM
Your clone 👇 
Screen Shot 2020-07-01 at 12 04 40 AM
- **More Stories**

- [ ] The elements in this section also need a bit more padding between each article as well as the images and the text. 
Your clone 👇 
Screen Shot 2020-07-01 at 12 06 19 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 06 40 AM

- **Opinion**

- [ ] The opinion section is missing its header. 
The original page 👇 
Screen Shot 2020-07-01 at 12 07 29 AM
Your clone 👇 
Screen Shot 2020-07-01 at 12 07 50 AM

- [ ] Please add more space between the images and the text as well as each element in the opinion section. 
Your clone 👇 
Screen Shot 2020-07-01 at 12 08 29 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 08 46 AM

- **Featured Slideshow**

- [ ] Please add more spacing between the sections.
Your clone 👇 
Screen Shot 2020-07-01 at 12 09 52 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 10 19 AM

- [ ] Please add more spacing between the images and the text in the elements on the side of the featured slideshow section. 
Your clone 👇 
Screen Shot 2020-07-01 at 12 11 03 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 11 24 AM
- **Subscribe and Newsletter**



- [ ] You did a really good job on this section! Please jusr ensure that both the subscribe and newsletter elements are vertically aligned well. 
Your clone 👇 
Screen Shot 2020-07-01 at 12 12 42 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 13 19 AM

- [ ] Additionally, please reduce some of the left spacing between the text and the images in the subscribe section. 
The original page 👇 
Screen Shot 2020-07-01 at 12 13 55 AM
Your clone 👇 
Screen Shot 2020-07-01 at 12 14 12 AM
- **Footer**

- [ ] The elements in your footer are not spaced properly. Please compare your clone with the original and fix this. 
Your clone 👇 
Screen Shot 2020-07-01 at 12 16 09 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 16 29 AM
### Medium screen


- **Navigation Bar**

- [ ] Please ensure that your navigation bar takes the full width of the page.
Your clone 👇 
Screen Shot 2020-07-01 at 12 17 23 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 17 43 AM

- **Footer**

- [ ] The elements in the footer are not like the original. Please fix this. 
Your clone 👇 
Screen Shot 2020-07-01 at 12 20 10 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 20 31 AM

### Small Screen
- **Navigation**

- [ ] Your navigation does not take up the full width on the small screen. Please fix this.
Your clone 👇 
Screen Shot 2020-07-01 at 12 21 31 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 22 16 AM
- **Subscribe**

- [ ] The text in the subscribe section is not like the original. Although it is in the middle of the page, the text in your clone appears to be left-aligned when it should be centered. Please fix this. 
Your clone 👇 
Screen Shot 2020-07-01 at 12 24 46 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 25 08 AM
- **Newsletter**

- [ ] The image for the newsletter section should disappear in the small screen. Please fix this. 
Your clone 👇 
Screen Shot 2020-07-01 at 12 25 59 AM
The original page 👇 
Screen Shot 2020-07-01 at 12 26 16 AM





### General

- [ ] The spacing issues that are present in the large screen are also present in the medium and small screens. Please fix these. 

- [ ] Please review your project for spelling mistakes. There are several areas where you have spelled things incorrectly. For example, you have put **"The DEPABATE"** instead of **"DEBATE"** and **"FEATURE"** instead of **"FEATURED"**.
### [OPTIONAL]

- While your linters are showing no errors, they are showing some warnings. Feel free to use the "Webhint Report" in the linters checks and fix those warnings.
Screen Shot 2020-07-01 at 12 29 37 AM


_P.S. all requested changes marked by [OPTIONAL] are not required. It is up to you whether or not you would like to do them_
****

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status requires changes :recycle: 
## Great job so far guys :tophat:  you have made a great clone :clap:  but in order to make it approved :white_check_mark:  you need to sharpen it a little bit :hammer: :toolbox: 

- [ ] Fix the header on small desktop views:
### clone: :point_down: :point_down: :point_down: :point_down:
image
### original:  :point_down: :point_down: :point_down: :point_down:
image

- [ ] Add some padding to this form so the text will not go to the extremes:
image

- [ ] the same form again need to be smaller on tabler views:
### clone: :point_down: :point_down: :point_down: :point_down:
image
 ### orignal: :point_down: :point_down: :point_down: :point_down:
image

- [ ] Fix the overlapping in the magazine section:
image
- [ ] also on mobile view there is the same issue:
image

- [ ] Fix the newsletter and subscribe section, on the desktop view, they should look exactly the same, you are missing the border on the newsletter and also the subscribe title should goes outside the container not inside:
### clone: :point_down: :point_down: :point_down: :point_down:
image

### original: :point_down: :point_down: :point_down: :point_down:
image

- [ ] Fix the width inside the subscribe section you need to make it a little bit wider:
image

- [ ] Fix the newsletter on the mobile view you need to remove the image and show only the form, as mentioned by the previous TSE:
### clone: :point_down: :point_down: :point_down: :point_down:
image
### original: :point_down: :point_down: :point_down: :point_down:
image

### Please make the required changes before requesting another code review.
## Happy Coding :tophat:

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Status: Changes required 🛑

## You have done an incredible job making this project.

### But I see that you have missed one change from the previous reviewer.

- There are still spacing issues all over your clone. Here are some of them I have pointed out:

Annotation 2020-07-03 013154

Annotation 2020-07-03 013315

Annotation 2020-07-03 013339

Annotation 2020-07-03 013403

Annotation 2020-07-03 013439

Annotation 2020-07-03 013520

Annotation 2020-07-03 013539

Annotation 2020-07-03 013907

Annotation 2020-07-03 014000

Annotation 2020-07-03 014032

*The above are just a few places I have pointed out. Be sure to go through your clone and add space where necessary.*

- Decrease width 👇

image

<hr>

Apply these changes and request another review.

Happy coding 👨‍💻

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status: require changes :recycle: 
## Great job guys :clap: :100:  you are almost there :checkered_flag:  , thank you for making some of the required changes, :warning: I have noticed that you have skipped some requirements please return back and fix them, to make your project approved.

- [ ] I'm talking about this [review](https://github.com/balerum03/newsweekclone/pull/3#pullrequestreview-440561408) and this [one](https://github.com/balerum03/newsweekclone/pull/3#pullrequestreview-441991066) also.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you are stuck or have any question don't hesitate to contact me on slack you can find me as **@Zakariae El Mejdki**_

**Review by HADDADSOHAIB — APPROVED** [review]
### Status: Project Approved :+1: 

### Hi @balerum03   :hand: 

### You did great with the project, you implemented all changes required with the previous TSEs, you can go on and merge this branch into master.However, there is some [Optional] changes that you can do before

- [Optional] Use the `<main>` tag to wrap the main part of the page.

**Pull request merged**
